/*******************************************************************************
 * Copyright (c) 2012, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

#ifndef __STD_POSIX_H__
#define __STD_POSIX_H__

#include <cpio.h>           /* Magic numbers for the cpio archive format. */
#include <dirent.h>         /* Allows the opening and listing of directories. */
#include <fcntl.h>          /* File opening, locking and other operations. */
#include <grp.h>            /* User group information and control. */
#include <pthread.h>        /* Defines an API for creating and manipulating POSIX threads. */
#include <pwd.h>            /* passwd (user information) access and control. */
#include <sys/ipc.h>        /* Inter-process communication (IPC). */
#include <sys/msg.h>        /* POSIX message queues. */
#include <sys/sem.h>        /* POSIX semaphores. */
#include <sys/stat.h>       /* File information (stat et al.). */
#include <sys/time.h>       /* Time and date functions and structures. */
#include <sys/types.h>      /* Various data types used elsewhere. */
#include <sys/utsname.h>    /* uname and related structures. */
#include <sys/wait.h>       /* Status of terminated child processes (see wait). */
#include <tar.h>            /* Magic numbers for the tar archive format. */
#include <termios.h>        /* Allows terminal I/O interfaces. */
#include <unistd.h>         /* Various essential POSIX functions and constants. */
#include <utime.h>          /* inode access and modification times. */

#endif /* __STD_POSIX_H__ */
