/*******************************************************************************
 * Copyright (c) 2012, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

#ifndef __STD_CPP_H__
#define __STD_CPP_H__

#include <cassert>     /* Diagnostics. */
#include <cctype>      /* Character class tests. */
#include <cerrno>      /* Error codes reported by (some) library functions. */
#include <cfloat>      /* Implementation-defined floating-point limits. */
#include <ciso646>     /* Programming in ISO 646 variant character sets. */
#include <climits>     /* Implementation-defined limits. */
#include <clocale>     /* Locale-specific information. */
#include <cmath>       /* Mathematical functions. */
#include <csetjmp>     /* Non-local jumps. */
#include <csignal>     /* Signals. */
#include <cstdarg>     /* Variable argument lists. */
#include <cstddef>     /* Definitions of general use. */
#include <cstdio>      /* Input and output. */
#include <cstdlib>     /* Utility functions. */
#include <cstring>     /* String functions. */
#include <ctime>       /* Time and date functions. */
#include <cwchar>      /* Manipulation of wide streams and several kinds of strings using wide characters. */
#include <cwctype>     /* Wide characters classification. */

#include <exception>
#include <fstream>
#include <ios>
#include <iostream>
#include <istream>
#include <iterator>
#include <limits>
#include <list>
#include <locale>
#include <map>
#include <memory>
#include <ostream>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <streambuf>
#include <string>
#include <typeinfo>
#include <utility>
#include <vector>

#endif /* __STD_CPP_H__ */
